# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-09-22 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0003_auto_20180922_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='added_at',
            field=models.DateTimeField(),
        ),
    ]
